#!/usr/bin/env python3
"""sync_thesis_figs.py — refresh every thesis-referenced figure in the
canonical fork (Universe Simulation Thesis/figures/) from the fresh
2026-09-22 post-retrain artifacts.

Sources:
  plots/                      7 regen-rendered top-level figures
  thesis_figures/             regenerated per-N composites + dashboards
  real_case_validation/       per-N OOD report figures (dashboard,
                              trajectory_GNN per preset, energy drift)

Also refreshes plots/stability_N*.png from the corrected thesis_figures
renders, and rewrites the fork's figures/MANIFEST.txt.
"""
from __future__ import annotations

import shutil
from pathlib import Path

REPO = Path(__file__).resolve().parent
FORK = REPO / "Universe Simulation Thesis"
FORK_FIG = FORK / "figures"

N_VALS = [10, 25, 50, 100]
PRESETS = [
    "full_solar_system",
    "sun_earth_only",
    "sun_planets_moon",
    "inner_planets",
    "jupiter_galileans",
    "solar_system_extended",
]
PCODE = {
    "full_solar_system":     "fss",
    "sun_earth_only":        "seo",
    "sun_planets_moon":      "spm",
    "inner_planets":         "ip",
    "jupiter_galileans":     "jg",
    "solar_system_extended": "sse",
}

MANIFEST: list[tuple[str, str]] = []
MISSING: list[str] = []


def cp(src: Path, dst: Path) -> None:
    if not src.is_file():
        MISSING.append(str(src))
        return
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    try:
        tgt = dst.relative_to(FORK).as_posix()
    except ValueError:
        tgt = dst.relative_to(REPO).as_posix() + "  (root refresh)"
    MANIFEST.append((src.relative_to(REPO).as_posix(), tgt))


def main() -> None:
    # 0. refresh the root plots/ stability per-N renders (they were the
    #    broken regen_top_level_plots versions)
    for n in N_VALS:
        cp(REPO / "thesis_figures" / f"stability_N{n}.png",
           REPO / "plots" / f"stability_N{n}.png")

    # 1. top-level plots/
    for f in ["eval_benchmark.png", "scaling_latency.png",
              "stability_N10.png", "stability_N25.png",
              "stability_N50.png", "stability_N100.png",
              "stability_overview.png"]:
        cp(REPO / "plots" / f, FORK_FIG / f)

    # 2. thesis_figures/
    for n in N_VALS:
        cp(REPO / "thesis_figures" / f"eval_benchmark_N{n}.png",
           FORK_FIG / f"eval_benchmark_N{n}.png")
        cp(REPO / "thesis_figures" / f"loss_curves_N{n}.png",
           FORK_FIG / f"loss_curves_N{n}.png")
        cp(REPO / "thesis_figures" / f"stability_N{n}.png",
           FORK_FIG / f"stability_N{n}.png")
    for f in ["dashboard.png", "param_count.png", "scaling_plot.png"]:
        cp(REPO / "thesis_figures" / f, FORK_FIG / f)

    # 3. per-N audit dashboards + headline-preset energy
    for n in N_VALS:
        cp(REPO / "real_case_validation" / f"report_N{n}" / "dashboard.png",
           FORK_FIG / f"dashboard_N{n}.png")
        cp(REPO / "real_case_validation" / f"report_N{n}"
           / "preset_full_solar_system" / "energy.png",
           FORK_FIG / f"energy_N{n}_fss.png")

    # 4. per-(N, OOD preset) trajectory_GNN (4 N x 6 OOD = 24)
    for n in N_VALS:
        for p in PRESETS:
            cp(REPO / "real_case_validation" / f"report_N{n}"
               / f"preset_{p}" / "trajectory_GNN.png",
               FORK_FIG / f"traj_N{n}_{PCODE[p]}_GNN.png")

    # 5. wholesale refresh of the fork's real_case_validation report tree
    import shutil as sh
    rcdst = FORK_FIG / "real_case_validation"
    if rcdst.is_dir():
        sh.rmtree(rcdst)
    for n in N_VALS:
        src_dir = REPO / "real_case_validation" / f"report_N{n}"
        if src_dir.is_dir():
            sh.copytree(src_dir, rcdst / f"report_N{n}",
                        ignore=sh.ignore_patterns("*.pt", "*.npz",
                                                  "rerun.log", "*.log",
                                                  "single_step"))
    n_rc = sum(1 for _ in rcdst.rglob("*.png"))
    print(f"  real_case_validation tree: {n_rc} PNGs copied")

    # 6. rewrite the fork manifest
    lines = ["# figures/MANIFEST.txt",
             "# Regenerated by sync_thesis_figs.py from the fresh",
             "2026-09-22 post-retrain artifacts.",
             "source -> target", ""]
    for s, t in MANIFEST:
        lines.append(f"{s} -> {t}")
    (FORK_FIG / "MANIFEST.txt").write_text("\n".join(lines) + "\n",
                                           encoding="utf-8")

    print(f"  flat figures copied: {len(MANIFEST)}")
    if MISSING:
        print("MISSING SOURCES:")
        for m in MISSING:
            print("  " + m)
        raise SystemExit(1)
    print("OK")


if __name__ == "__main__":
    main()